### ISSUE TITLE
lastUpdatedSequence

### ISSUE THREAD

**Issue by alexblack** [sschendel/SyncManagerAndroid#1]
Hi, thanks for sharing this framework!  Could you write up a little bit on how to implement lastUpdatedSequence?

Is it as simple as: only modify it on the server, and, increment it each time a record is updated on the server?

Thanks!

**Comment by sschendel** [comment]
Glad you like the framework!  Implementation is kind of left up to user, and depends somewhat on the complexity of your sync needs.  A simple server only incrementing sequence definitely works in many use cases.  

In my demo app that syncs with Google Tasks API [SyncManagerAndroid-DemoGoogleTasks](https://github.com/sschendel/SyncManagerAndroid-DemoGoogleTasks) I do exactly that.  

I map the Google Task resource "updated" datetime field to lastUpdatedSequence.
[Google Task API - Task resource](https://developers.google.com/google-apps/tasks/v1/reference/tasks#resource)

Hope this helps some.

**Comment by alexblack** [comment]
Hi, thanks for the info.  

It seems like the client needs to update this field though, otherwise local changes won't make it up to the server.  Does that sound right to you?

Imagine client and server are synced, and a record changes on the client, the SyncManager.sync is only going to update the remote item if the local item has a newer lastUpdatedSequence.

If clients increment values, then you can probably run into issues where two clients both increment the value, one syncs, then when the second syncs it looks like everything is up to date since his locally incremented value is the same as what the other client updated things to.

**Comment by sschendel** [comment]
You are correct.  My demo app does not allow local updates.  The remote Google Task API "updated" field is an RFC 3339 UTC timestamp that is mapped to "lastUpdatedSequence" syncable field as UNIX time seconds.  If (when) an edit feature were to be added to the demo app I would set this field locally on update.

**Comment by sevar83** [comment]
Hi, is it correct and safe if on update the client sets the lastUpdatedSequence with its own device time? The server and device clocks may have some difference (not timezone difference). I'm going to design my own API so is it generally a better idea to use incremental sequence counter instead of timestamp of last update?

10x for the cool framework! Beautiful work!

**Comment by sschendel** [comment]
Thanks for the kind words.  I think having both the client and server update lastUpdatedSequence using UTC timestamp is a good, simple approach (mileage may vary - depending on the nature of your data and frequency of change - among other factors).  SyncManagerAndroid is fairly simple in it's strategy for conflict resolution.  Most recent update wins.  I would like to continue to evolve the framework to provide more robust sync options.  For now it is simple.  This article has some good information on data synchronization: https://msdn.microsoft.com/en-us/sync/bb887608.aspx
