### ISSUE TITLE
deleted records

### ISSUE THREAD

**Issue by mcelotti** [sschendel/SyncManagerAndroid#2]
Hi, first of all thanks for sharing and congrats for the framework!
I see that there's no implementation for the deleted records, what do you think about a soft-delete approach?
We could have a "setDeleted" and "isDeleted" in Syncable interface (and some changes in the SyncManager and Datastore too).
This feature raises the problem: what happens when a user (A) updates a record that another user (B) has deleted?
As a starting point I think that once a record has been set as deleted it's gone, no matter further updates, so on next sync user (A) should get - ie update - the record as deleted, and that's all.

Thanks,
Marco

**Comment by sschendel** [comment]
Thanks for the comment, Marco.  The way sync is implemented in the framework is simple - and really just a starting point.  Soft delete could be handled as an update.  In the scenario you mention the most recent "update" would win.  Adding further sophistication to the sync implementation would be required to deterministically resolve the scenario.  Your suggestion of recognizing a "deleted" state is one way to handle it.  In a future state of the framework I would like to be able to plugin different sync strategies.
